### ISSUE TITLE
Attributes not pulling down correctly

### ISSUE THREAD

**Issue by neddytheman** [DavidFW1960/ABB-Home-Assistant-Usage#3]
Hey David,

I am having some issues with the script - It doesn't seem to be pulling down the correct values...
I've done some investergation a little and here is the parts that might help.. (Also happy to chat on Discord or directly Nedwos / neddy@matrix.net.au
As i haven't been able to get the correct data into the sensor i haven't gotten any further on this!

**DATA pulled from myaussie-api (Manually from browser)**
{"usedMb":2597951,"downloadedMb":2203416,"uploadedMb":394535,"remainingMb":null,"daysTotal":31,"daysRemaining":7,"lastUpdated":"2020-04-15 19:51:36"}

**DATA pulled when i run the script manually..**
config $ ./abbusage_ha.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    47  100    30  100    17     40     22 --:--:-- --:--:-- --:--:--    63
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    30  100    30    0     0     43      0 --:--:-- --:--:-- --:--:--    43
date: invalid date 'null'
{"attributes": {"allowanceMb": 100000000, "daysRemaining": null, "daysTotal": null, "daysUsed": 0, "downloadedMb": null, "entity_picture": "/local/icons/abb/abb.png", "friendly_name": "ABB Usage", "icon": "mdi:blank", "lastUpdated": "2020-04-15T+08:00", "nextRollover": "1970-01-01T00:00:00+08:00", "remainingMb": null, "uploadedMb": null, "usage": "", "usedMb": null}, "context": {"id": "e16e7c00f2cc4f99adbd257577d42484", "parent_id": null, "user_id": "3e8538d75cf843e484684b0cf86fe8c9"}, "entity_id": "sensor.abb_usage", "last_changed": "2020-04-15T12:11:30.538173+00:00", "last_updated": "2020-04-15T12:11:30.538173+00:00", "state": ""}config $

**Attributes on the entity (sensor.abb_useage)**
usage: 
usedMb: null
downloadedMb: null
uploadedMb: null
remainingMb: null
daysTotal: null
daysRemaining: null
lastUpdated: 2020-04-15T+08:00
nextRollover: 1970-01-01T00:00:00+08:00
daysUsed: 0
allowanceMb: 100000000
friendly_name: ABB Usage
icon: mdi:blank
entity_picture: /local/icons/abb/abb.png

**Comment by DavidFW1960** [comment]
Did you run the setup script first?
Will try and get you on discord. I'm sorry I only just saw this...

**Comment by neddytheman** [comment]
Hey David, Yes tried a bunch of things... i am in the HA discords, username Nedwos

**Comment by DavidFW1960** [comment]
I can't find you on discord. My ID there is the same as ID here on github

**Comment by DavidFW1960** [comment]
ok found you on HA lol
