### ISSUE TITLE
Unlimited vs limited total data usage

### ISSUE THREAD

**Issue by teda-229** [DavidFW1960/ABB-Home-Assistant-Usage#4]
Hey Dave,

Thanks for this tool, super useful and as a new home assistant user - much appreciated. My data is limited to 500GB rather than unlimited per your example. On your lovelace.txt file line 9 calls this attribute allowanceMb, where as on sensor.abb_usage this attribute is remainingMb.

At line 49 the reference to vars[4] then pulls the remaining data, rather than the total. I've changed this in my code to being (vars[2] +vars[3] +vars[4]) / 1000).

Hope this helps, and thanks again!
Tom

**Comment by DavidFW1960** [comment]
Um... it should cope with limited plans.. when I wrote it it did. Has ABB changed their API? I am not with ABB anymore.

**Comment by teda-229** [comment]
Everything still works and pulls down ok. Looks like just one parameter has changed from total data to remaining data. I tweaked the card to suit.

**Comment by DavidFW1960** [comment]
Can you pull down the json the script is seeing and email it to me? david@wilfam.net or even better allow me to login with your username and password so I can see what is happening and fix it for other people? Or make a PR here but you'll need to show me that json as I am not with ABB anymore..
