### ISSUE TITLE
FYI, We added ABB into core!

### ISSUE THREAD

**Issue by Bre77** [DavidFW1960/ABB-Home-Assistant-Usage#5]
Hey David, just wanted to make you aware that @nickw444 and I have built ABB functionality into Home Assistant core. If you have any suggestions/improvements based your existing implementation, let me know or raise a PR.

https://rc.home-assistant.io/integrations/aussie_broadband/

**Comment by DavidFW1960** [comment]
Thanks Brett. I noticed that in the release notes (I run the betas). Good job. I'm not running with ABB anymore but good to know this is now available for people that are,
